// <auto-generated />
namespace Trash_Collector.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedcustomersemployeesandadmincontrollers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedcustomersemployeesandadmincontrollers));
        
        string IMigrationMetadata.Id
        {
            get { return "201707042257168_added customers, employees, and admin controllers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
