// <auto-generated />
namespace Trash_Collecter_Main.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Createtablesandroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Createtablesandroles));
        
        string IMigrationMetadata.Id
        {
            get { return "201706291658593_Create tables and roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
